In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
import random

In [8]:
# IMPUTATION
data={"id":[1,2,3,4,5,6],
     "age":[25,np.nan,30,35,np.nan,100],
     "salary":[50000,60000,np.nan,80000,90000,np.nan],
     "city":["New York","London",np.nan,"Parish","London",np.nan]
     }
df=pd.DataFrame(data)
print('Original Data :')
df

Original Data :

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2    NaN  60000.0    London
2   3   30.0      NaN       NaN
3   4   35.0  80000.0    Parish
4   5    NaN  90000.0    London
5   6  100.0      NaN       NaN

In [9]:
# "Mean Imputer"
mean_imputer=SimpleImputer(strategy='mean')
df_mean=df.copy()
df_mean[['age','salary']]=mean_imputer.fit_transform(df_mean[['age','salary']])

print("\nMean Imputed Data:")
display(df_mean)

Mean Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   47.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0    Parish
4   5   47.5  90000.0    London
5   6  100.0  70000.0       NaN

In [10]:
# "Median Imputer"
median_imputer=SimpleImputer(strategy='median')
df_median=df.copy()
df_median[['age','salary']]=median_imputer.fit_transform(df_median[['age','salary']])

print("\nMedian Imputed Data:")
display(df_median)

Median Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   32.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0    Parish
4   5   32.5  90000.0    London
5   6  100.0  70000.0       NaN

In [11]:
# Mode imputer
mode_imputer = SimpleImputer(strategy='most_frequent')
df_mode=df.copy()
df_mode[['age','salary','city']]=mode_imputer.fit_transform(df_mode[['age','salary','city']])
print("\nMode Imputed Data:")
display(df_mode)

Mode Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   25.0  60000.0    London
2   3   30.0  50000.0    London
3   4   35.0  80000.0    Parish
4   5   25.0  90000.0    London
5   6  100.0  50000.0    London

In [14]:
# Random Simpling Imputation
df_random=df.copy()

def random_impute(series):
    # drop nan value to avoid errors
    filled= series.dropna().tolist()
    return series.apply(lambda x:random.choice(filled) if pd.isnull(x) else x)

for col in ['age','salary','city']:
    df_random[col]=random_impute(df_random[col])

print('\nRandom Sampling Imputed Data:')
display(df_random)

Random Sampling Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   35.0  60000.0    London
2   3   30.0  80000.0    London
3   4   35.0  80000.0    Parish
4   5   25.0  90000.0    London
5   6  100.0  50000.0    Parish

In [6]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\anaconda3\envs\genai_env\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2