In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Create sample dataset
df = pd.DataFrame({
    'Age': [18,22,30,45,60,80,25,35,50,70],
    'Salary': [20000,250000,40000,60000,120000,100000,30000,50000,80000,150000],
    'Purchased': [0,0,0,1,1,1,0,1,1,1]
})
print("Original Data:")
display(df)

# 2. Define Features (X) and target (y)
X = df[['Age', 'Salary']]
y = df['Purchased']
#3. Split dataset (80%train , 20% testing)
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)
#4. Show Result
print("\nTraining Features:")
display(X_train)
print("\nTraining Target:")
display(y_train)

print("\nTesting Features:")
display(X_test)
print("\nTesting Target:")
display(y_test)

print("\nShapes:")
print("X_Train:",X_train.shape)
print("X_Test:",X_test.shape)
print("y_Train:",y_train.shape)
print("y_Test:",y_test.shape)

Original Data:

   Age  Salary  Purchased
0   18   20000          0
1   22  250000          0
2   30   40000          0
3   45   60000          1
4   60  120000          1
5   80  100000          1
6   25   30000          0
7   35   50000          1
8   50   80000          1
9   70  150000          1

Training Features:

   Age  Salary
5   80  100000
0   18   20000
7   35   50000
2   30   40000
9   70  150000
4   60  120000
3   45   60000
6   25   30000

Training Target:

5    1
0    0
7    1
2    0
9    1
4    1
3    1
6    0
Name: Purchased, dtype: int64

Testing Features:

   Age  Salary
8   50   80000
1   22  250000

Testing Target:

8    1
1    0
Name: Purchased, dtype: int64

Shapes:
X_Train: (8, 2)
X_Test: (2, 2)
y_Train: (8,)
y_Test: (2,)